### ISSUE TITLE
Meetup : 34 | Planner

### ISSUE THREAD

**Issue by dwdraju** [DevOps-Kathmandu/Meetups#4]
# Event Details

**Meetup No** : 34
**Proposed date**  : 26th April, 2024, 5PM-7PM UTC+5:45 
**Confirmed date** :  26th April, 2024, 5PM-7PM UTC+5:45

**Meetup:**         https://www.meetup.com/DevOps-Kathmandu/events/
**Meetup Link:** https://www.meetup.com/devops-kathmandu/events/300306044/

## Speaker Bio 
**Balman Rawat** | Devops Engineer from Bhaktapur. Currently working as a DevOps Contractor for Proxify and Alumni of CloudFactory.

Github: https://github.com/rbalman
Linkedin: https://www.linkedin.com/in/rbalman

---

**Ashok Pokharel** | DevOps Engineer, Security Consultant, Full Stack Web

Linkedin: [linkedin.com/in/ashokpokharel977](https://www.linkedin.com/in/ashokpokharel977/)
Github: https://github.com/ashokpokharel977

## Meetup Description

**Title:**  34th Meetup | Container Internals, Secure AWS Architecture

**Description:** We warmly invite you to attend the 34th episode of DevOps Kathmandu in person, featuring engaging discussions on Container Internals and Architecting AWS with a focus on security.

## Resources
**Curation:**       https://github.com/DevOps-Kathmandu/curation
**Youtube:**       https://www.youtube.com/channel/UChIow3i-WObHKidPD_xwwlA/videos
**Slack:**           http://bit.ly/devops-kathmandu-slack
**Q/A docs:**     http://bit.ly/devops-kathmandu-area.
 
## Actions / Flow
- [ ] Choose lead organizer for catching up the flow
- [x] Publish for seeking speakers and sponsors
- [x] Confirm date and time with speaker
- [x] Confirm venue
- [x] Confirm parking in venue for 2/4 wheels
- [x] Finalize sponsor
- [x] Collect speakers { bio, meetup title, description, photo }
- [x] Media banner with speaker photo
- [x] Publish to meetup group
- [x] Announce to email, linkedin
- [x] Reminder message to attendees T-1
- [x] Shared on media: twitter, facebook groups, slack
- [ ] Update Q/A docs
- [x] Send thank you not to speakers and host. Also, ask speakers add slides on community google drive folder
- [x] Confirm slides from speakers
- [ ] Send thanks and review forms to attendees via meetup. Include slides and videos if available
- [ ] Do a retro and share outcomes in this issue

**Comment by omegazyadav** [comment]
Do we have speaker confirmed for this event ? 
cc: @thapakazi @dwdraju

**Comment by dwdraju** [comment]
Speakers not yet finalized @omegazyadav

**Comment by noots-globally** [comment]
Hi Organizers and Community members, 

I run the tech department in Globalyhub. We build SaaS products for international market and are interested to provide venue for this meetup. 

We have a dedicated event space in our office that can seat ~50 people comfortably. We are located in Kumaripati, Lalitpur. [Link to google maps](https://maps.app.goo.gl/fFvoX5hXJQ5cZaNMA)


There's plenty of street parking for bikes and scooters. We also have an underground parking space that will fit about 2 cars. If we start in the evening, there's usually ample street parking on the main road.  There are also paid options nearby, such as [this one](https://maps.app.goo.gl/E3uLypcVAzMMR7237) which is 5 mins walk from the venue. 


We're also open to provide sponsorships to cover (some of) the meetup costs. Please let me know if there's any sponsorship model that the meetup has . 


Also happy to help out with any organising tasks! 

Cheers,
Nootan

**Comment by Aju100** [comment]
Hi @noots-globally, We are still looking for potential speakers either physical or online. If you know please let us know so we can reach out to them. Once we decide on this finalization of the speaker, we will decide on the venue. Cheers : D

**Comment by dwdraju** [comment]
Thanks @noots-globally for offering the venue. The description is a fit for us. Are you okay for the date/time 26th April, 2024, 5PM-7PM UTC+5:45?

About sponsorships, the venue is expected to provide space, mics, speakers and tea-coffee-cookies. We have 10-15 minutes coffee break between sessions as a part of socializing. 

And 1-2 slots of 5 minutes for sponsors to pitch product/tool/services and job vacancy aligning with our meetup theme and sponsor snacks/goodies for the event.

**Comment by noots-globally** [comment]
The date and time sounds good for us! Let's lock it in!

**Comment by nootanghimire** [comment]
Hi organizers, 

I reached out to my network and @ashokpokharel977 is interested to be part of the meetup as a speaker. We chatted a bit about the topics and since he primarily works with AWS, it'll likely be related to that. 

@ashokpokharel977 , It was nice talking to you over the phone. I'll let the organizers move forward with the process. 


cc @Aju100 @dwdraju @omegazyadav @thapakazi

**Comment by hfbalman** [comment]
Hi guys,

I would like to show my interest this time on sharing my experience in learning the internals of container 🚢  technology. My objective to share my experience and at the same letting know of the fundamentals of container technology is a simplest possible way. I am planning to show case step by step commands and examples that will take audiences through the journey however,  I haven't finalized the title and content so far but showing my interest. 😄 

Thanks.

**Comment by rbalman** [comment]
Hi guys,

I would like to show my interest this time on sharing my experience in learning the internals of container 🚢  technology. My objective to share my experience and at the same letting know of the fundamentals of container technology is a simplest possible way. I am planning to show case step by step commands and examples that will take audiences through the journey however,  I haven't finalized the title and content so far but showing my interest. 😄 

Thanks.

**Comment by omegazyadav** [comment]
My vote is for `1. Architecting on AWS from a Security Lens`.

**Comment by thapakazi** [comment]
Thanks you guys for your interest as speaker :) 
@rbalman and @ashokpokharel977 

We just sent you an email to confirm the topics.
Cheers 🎉

**Comment by dwdraju** [comment]
Will publish the event in [meetup page](https://www.meetup.com/devops-kathmandu/) by start of next week. Happy new year to all 🎉

**Comment by nootanghimire** [comment]
Hi guys, 

Just revised the design and added a QR code for the RSVP link. I've also taken the liberty to add sponsorship logos. The designs are in Canva as well. 

![Blue Modern Business Conference Facebook Post (1)](https://github.com/DevOps-Kathmandu/Meetups/assets/2210043/9b6200bf-66e2-476f-b21b-cb9942ad6555)

**Comment by dwdraju** [comment]
Thanks @nootanghimire. Sadly, the photo doesn't match the specification to fit as Featured photo
on meetup.com event. Should be at least 1200 x 675 pixels.
![Uploading Screenshot 2024-04-17 at 18.06.12.png…]()

**Comment by dwdraju** [comment]
Thanks all for making this event a success. We will post more after doing a retro soon.

**Comment by dwdraju** [comment]
Hi @rbalman @ashokpokharel977 , can you please add the slides on [this google drive folder](https://drive.google.com/drive/folders/1FjXl_E4scyHUWW3pR3BSfH0PVHa1qw-O?usp=drive_link)? Thanks!
