### ISSUE TITLE
Meetup : 35 | Planner

### ISSUE THREAD

**Issue by omegazyadav** [DevOps-Kathmandu/Meetups#6]
# Event Details

**Meetup No** : 35
**Proposed date**  : August 16th
**Mode** : Offline
**Confirmed date** :  August 16th

**Meetup:**         https://www.meetup.com/DevOps-Kathmandu/events/
**Meetup Link:** https://www.meetup.com/devops-kathmandu/events/302670562

## Speaker Bio
**Speaker 1: Sudeep Bhandari**
Software Engineer / DevOps Engineer
Linkedin: [https://www.linkedin.com/in/sudeephb/](https://www.linkedin.com/in/sudeephb/)
Github: [https://github.com/sudeephb](https://github.com/sudeephb)

---

**Speaker 2: Milan Thapa** 
Ops guy aspiring to be dev
Website: [https://thapakazi.com/](https://thapakazi.com/)
Twitter: [https://x.com/thapakazi_](https://x.com/thapakazi_)

## Meetup Description

**Title:**  35th Meetup | Creating software to Monitor Hardware
**Description:** We warmly invite you to attend the 35th episode of DevOps Kathmandu in person meetup, featuring engaging discussions on Creating Software to Monitor Hardware, Simplify Your Docker Workflow with Lazydocker and awesome interaction with fellow DevOps.

## Resources
**Curation:**       https://github.com/DevOps-Kathmandu/curation
**Youtube:**       https://www.youtube.com/channel/UChIow3i-WObHKidPD_xwwlA/videos
**Slack:**           http://bit.ly/devops-kathmandu-slack
**Q/A docs:**     http://bit.ly/devops-kathmandu-area.
 
## Actions / Flow
Step 1(Pre plan)
- [x] Choose a lead organizer for catching up the flow and at least two organizers
- [x] Create a centralized google doc for the meetup inside community google drive for writing updates
- [x] Publish for seeking speakers and sponsors
- [x] Confirm date and time with speaker
- [x] Confirm venue(Requirement: wireless mic and speaker, max 60, spacious hall, water-tea-coffee-cookies, parking space, food court)
- [x] Confirm parking in venue for 2/4 wheels
- [x] Finalize sponsor
- [x] Finalize speaker
- [x] Collect speakers { bio, meetup title, description, time limit, target audience, photo, phone number for emergency updates(cancellation, time change, etc.) in centralized google doc }

Step 2(Ready for it!)
- [x] Media banner with speaker photo
- [x] Publish to meetup group and make announcement at least 10 days before event
- [x] Inform speaker about publication of event and send link along with RSVP summary. Also, send google calendar invite with meet link to use in meetup day for screenshare recording
- [x] Announce to email, linkedin, twitter, slack, discord
- [x] Reminder message to attendees T-1(Include time, venue map & routes, parking options)

Step 3(Meetup Day)
- [x] Paste venue direction and meetup info in A4 sheets if required
- [x] Manage water, tea, coffee, cup, chairs
- [x] Mic, speaker, projector test
- [x] Start screenshare of speaker via pre-generated meet url 
- [x] Update Q/A docs(for online meetup)

Step 4(Post Meetup)
- [x] Send thank you note to speakers and host. Also, ask speakers to add slides on community google drive folder
- [x] Confirm slides from speakers
- [x] Send thanks and review forms to attendees via meetup. Include slides and videos if available
- [ ] Do a retro and share outcomes in this issue

**Comment by isunp** [comment]
Hello Organizers and Community members,

I'm reaching out from [Adex](adex.ltd), an AWS Advanced Tier Partner specializing in cloud consulting. We don't just provide cloud solutions; we work alongside organizations to reimagine business processes and operating models through the power of cloud-enabled platforms. 

We're excited to offer our resources to support community meetups, and our goal is to provide a space for fostering collaboration and knowledge sharing within the community. 

We have a dedicated event area in our Ekantakuna office that can comfortably seat up to 50 people. This space is perfect for hosting meetups, workshops, or any other gathering that aims to bring people together. There's ample parking for scooters and bikes for attendees, and underground car parking is also available. [(link to Google Maps)](https://maps.app.goo.gl/cBAk1gFQhrUbkgNA7)
We're happy to go beyond just offering a physical space; if you're looking for financial backing for our meetups and events, we're open to discussing sponsorship options. 

Adex's team of cloud consultants can also be a valuable asset to our meetup. We can offer our expertise on cloud-related topics and potentially assist with presentations or workshops related to the cloud.

Regards,
Sachin Pandey

**Comment by omegazyadav** [comment]
Hi @isunp, 

We appreciate your interest in offering the venue and other resources to support the community meetups. Our meetup usually has around 50 participants, which aligns with the capacity you mentioned.  Also, we have confirmed for the 16th of August. 

We would love to talk about the sponsorship beyond the physical space. As part of our event, we significantly emphasize networking sessions. These sessions provide attendees with the invaluable opportunity to engage with one another, share insights, discuss potential collaborations, and build professional relationships. To enhance these networking experiences, we usually offer refreshments such as cookies, coffee, beverages(soft drinks), and pizza. If you can sponsor these items, that would be great. 

Also, Could you please let us know if the venue provides microphones and any related audio equipment for speaker sessions?

Thank you in advance for your assistance. We look forward to hosting our event at Adex. 

Best Regards,
Yadav Lamichhane

**Comment by isunp** [comment]
Hi @omegazyadav 
I had a discussion internally and we can only provide tea, coffee, and cookies as refreshments for the networking sessions. Unfortunately, we are unable to extend our support to include soft drinks, or pizza at this time.

**Comment by dwdraju** [comment]
The meetup event is published: https://www.meetup.com/devops-kathmandu/events/302670562/

**Comment by dwdraju** [comment]
Thanks @isunp for the coordination and support. Could you please write a short venue directions and parking instructions for the event day?

**Comment by dwdraju** [comment]
Banner for social media: ![banner](https://github.com/user-attachments/assets/67d035ed-d2f1-4543-bd11-e6655ef019a0)
![banner2](https://github.com/user-attachments/assets/cc9d160c-0eff-4a56-a93f-12279709230f)

**Comment by dwdraju** [comment]
Linkedin update: https://www.linkedin.com/feed/update/urn:li:activity:7228781180760838145

**Comment by isunp** [comment]
Thank you, @dwdraju, for the update. Regarding venue directions and parking, the venue is located behind the Switzerland Embassy, and there is parking available on the office premises as well as underground. Here is the Google Maps link attached: [Adex International](https://maps.app.goo.gl/ZGKgUzzuQRSQisqN7)

**Comment by dwdraju** [comment]
**Schedule for the meetup:**
1. Welcome & Networking: 5:00 PM - 5:15 PM
2. Session 1 by @sudeephb: 5:15 PM - 5:55 PM
3. Sponsor Acknowledgment: 5:55 PM - 6:00 PM
4. Session 2 by @thapakazi: 6:00 PM - 6:30 PM
5. Closing & Wrap-Up: 6:30 PM - 6:40 PM
6. </Pizza Time>

**Comment by dwdraju** [comment]
Shared album for event photos: [https://photos.app.goo.gl/aFxydUwGewk5nCa36](https://photos.app.goo.gl/aFxydUwGewk5nCa36)

Feel free to add photos you have taken in the album.

**Comment by dwdraju** [comment]
* Sent email to attendees with [feedback form](https://forms.gle/xgkTjBoRb5EaYVJc8)
* Slides link added: https://github.com/DevOps-Kathmandu/Meetups/tree/master/2024/20240816-%2335
